trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python 3.8'

- script: |
    python models/linear_regression/cars_linear_regression.py
    python models/decision_tree/cars_decision_tree.py
    python models/random_forest/cars_random_forest.py
  displayName: '🚂 Train All Models for cars'
    pip install -r environment/requirements_cars.txt
  displayName: 'Install dependencies'

- script: |
  displayName: 'Train all models'

- script: |
    python cd/evaluate_metrics.py cars LinearRegression
    python cd/evaluate_metrics.py cars RandomForest
    python cd/evaluate_metrics.py cars DecisionTree
  displayName: 'Evaluate model metrics'

- script: |
    python ci/compare_models.py cars
  displayName: 'Compare models and select best'

- script: |
    python cd/deploy_model.py cars
  displayName: 'Deploy best model'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'reports'
    ArtifactName: 'metrics_reports'
    publishLocation: 'Container'
  displayName: 'Publish metrics reports as artifact'